---
- name: Installing different pacakages
  hosts: 192.168.60.22
  tasks:
   - name: Install pacakages
     apt:
      name: "{{item.a}}"
      state: "{{item.b}}"
      update_cache: "{{item.c}}"
     with_items:
      - {a: tree,b: present,c: no}
      - {a: apache2,b: absent,c: no}
      - {a: git,b: latest,c: yes}


...
