---
- name: Configuring apache2
  hosts: 192.168.60.24
  tasks:
   - name: Installing apache2
     apt: 
      name: apache2
      state: present
   - name: Edit index.html file
     copy:
      content: "Home page of intelliq"
      dest: /var/www/html/index.html
   - name: Restart apache2
     service:
      name: apache2
      state: restarted
   - name: Check URL response
     uri:
      url: "http://192.168.60.24"
      status: 200
      



...
